language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: ddef8b24d6b0909e380102973fed25d35a71b3be
 local_dir: dist
 on:
   branch: master
